import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
import AboutMe from '@/components/AboutMe'
import NavBar from '@/components/NavBar'
import Projects from '@/components/Projects'
import Experience from '@/components/Experience'
import Skills from '@/components/Skills'
import Contact from '@/components/Contact'
import Intro from '@/components/Intro'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MyPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="portfolio.png" />
    
      </Head>
      <div className={styles.Home}>

      
      <NavBar></NavBar>

      <Intro></Intro> 

      <AboutMe></AboutMe> 

      <Projects></Projects>

      <Experience></Experience>

      <Skills></Skills>

      <Contact></Contact>
      </div>

    </>
  )
}
